server.address=0.0.0.0
server.port=8080
server.forward-headers-strategy=framework

spring.config.import=classpath:application-postgres.properties

spring.thymeleaf.cache=true
spring.jpa.show-sql=false

app.public-base-url=https://bruising-lizard-deflector.ngrok-free.dev
app.media.public-base-url=https://bruising-lizard-deflector.ngrok-free.dev/media
app.media.hint=JPG, PNG, WEBP lub GIF. Awatar do 5 MB, baner do 10 MB (zalecane 1920×336 px).
