spring.application.name=Politechnika-Monopoly

spring.profiles.active=localhost

server.port=${PORT:8080}

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.thymeleaf.cache=false

spring.web.resources.cache.period=0
spring.web.resources.chain.cache=false

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=12MB
