spring.config.import=classpath:application-postgres.properties

app.public-base-url=http://localhost:8080
app.media.public-base-url=http://localhost:8080/media
app.media.hint=JPG, PNG, WEBP lub GIF. Awatar do 5 MB, baner do 10 MB.
