spring.datasource.url=jdbc:postgresql://ep-damp-fire-alzendby-pooler.c-3.eu-central-1.aws.neon.tech/neondb?sslmode=require&currentSchema=monopoly&prepareThreshold=0&preparedStatementCacheQueries=0
spring.datasource.username=neondb_owner
spring.datasource.password=npg_tH0VgdZhBk8u
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=monopoly

spring.h2.console.enabled=false
