package pl.pb.monopoly.config;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.ApplicationArguments;
import org.springframework.boot.ApplicationRunner;
import org.springframework.core.annotation.Order;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Component;

import java.sql.Connection;
import java.sql.SQLException;

@Component
@Order(0)
public class DatabaseSchemaPatch implements ApplicationRunner {

    private static final Logger log = LoggerFactory.getLogger(DatabaseSchemaPatch.class);

    private final JdbcTemplate jdbcTemplate;

    public DatabaseSchemaPatch(JdbcTemplate jdbcTemplate) {
        this.jdbcTemplate = jdbcTemplate;
    }

    @Override
    public void run(ApplicationArguments args) {
        if (isH2()) {
            patchH2();
            return;
        }
        patchPostgres();
    }

    private void patchH2() {
        patch("ALTER TABLE game_players ADD COLUMN IF NOT EXISTS ready boolean NOT NULL DEFAULT false");
        patch("ALTER TABLE game_players ADD COLUMN IF NOT EXISTS doubles_count integer NOT NULL DEFAULT 0");
        patch("ALTER TABLE game_players ADD COLUMN IF NOT EXISTS rolls_this_turn integer NOT NULL DEFAULT 0");
        patch("ALTER TABLE game_players ADD COLUMN IF NOT EXISTS double_rent_next boolean NOT NULL DEFAULT false");
        patch("ALTER TABLE game_players ADD COLUMN IF NOT EXISTS jail_pass_active boolean NOT NULL DEFAULT false");
        patch("ALTER TABLE game_sessions ADD COLUMN IF NOT EXISTS leader_id bigint");
        patch("""
                CREATE TABLE IF NOT EXISTS game_invites (
                    id bigint generated by default as identity primary key,
                    session_id bigint not null,
                    inviter_id bigint not null,
                    invitee_id bigint not null,
                    status varchar(16) not null default 'PENDING',
                    created_at timestamp not null default current_timestamp
                )
                """);
        patch("ALTER TABLE player_statistics ADD COLUMN IF NOT EXISTS pending_wheel_card varchar(40)");
        patch("ALTER TABLE player_statistics ADD COLUMN IF NOT EXISTS pending_start_cash_bonus integer DEFAULT 0");
        patch("UPDATE player_statistics SET pending_start_cash_bonus = 0 WHERE pending_start_cash_bonus IS NULL");
        try {
            jdbcTemplate.execute("ALTER TABLE player_statistics ALTER COLUMN pending_start_cash_bonus SET NOT NULL");
        } catch (Exception ex) {
            log.debug("H2 pending_start_cash_bonus NOT NULL already set: {}", ex.getMessage());
        }
        patch("ALTER TABLE game_sessions ADD COLUMN IF NOT EXISTS pending_buyback_pos integer");
        patch("ALTER TABLE game_sessions ADD COLUMN IF NOT EXISTS pending_buyback_victim_id bigint");
        patch("ALTER TABLE game_sessions ADD COLUMN IF NOT EXISTS pending_buyback_holder_id bigint");
        patch("ALTER TABLE game_sessions ADD COLUMN IF NOT EXISTS pending_buyback_price integer");
        patch("ALTER TABLE users ADD COLUMN IF NOT EXISTS suspended boolean NOT NULL DEFAULT false");
        patch("ALTER TABLE users ADD COLUMN IF NOT EXISTS suspended_until timestamp");
        patch("ALTER TABLE users ADD COLUMN IF NOT EXISTS suspension_reason varchar(500)");
        patch("""
                CREATE TABLE IF NOT EXISTS user_warnings (
                    id bigint generated by default as identity primary key,
                    user_id bigint not null,
                    moderator_id bigint not null,
                    message varchar(500) not null,
                    created_at timestamp not null default current_timestamp
                )
                """);
        patchUsersDateOfBirthH2();
    }

    private void patchUsersDateOfBirthH2() {
        patch("ALTER TABLE users ADD COLUMN IF NOT EXISTS date_of_birth date");
        try {
            patch("UPDATE users SET date_of_birth = DATEADD('YEAR', -age, CURRENT_DATE) WHERE date_of_birth IS NULL");
        } catch (Exception ex) {
            log.debug("H2 age->date_of_birth migration skipped: {}", ex.getMessage());
        }
        patch("UPDATE users SET date_of_birth = DATEADD('YEAR', -25, CURRENT_DATE) WHERE date_of_birth IS NULL");
        try {
            patch("ALTER TABLE users ALTER COLUMN date_of_birth SET NOT NULL");
        } catch (Exception ex) {
            log.debug("H2 date_of_birth NOT NULL already set: {}", ex.getMessage());
        }
        try {
            patch("ALTER TABLE users DROP COLUMN IF EXISTS age");
        } catch (Exception ex) {
            log.debug("H2 drop age column skipped: {}", ex.getMessage());
        }
    }

    private void patchPostgres() {

        patch("""
                SET search_path TO monopoly, public;
                DO $$
                DECLARE r record;
                BEGIN
                  FOR r IN
                    SELECT c.conname
                    FROM pg_constraint c
                    JOIN pg_class t ON c.conrelid = t.oid
                    WHERE t.relname = 'game_sessions'
                      AND c.contype = 'f'
                      AND (c.conname LIKE '%pending%'
                           OR c.conname LIKE '%decider%'
                           OR c.conname LIKE '%upgrade%'
                           OR c.conname LIKE '%extra_roll%'
                           OR c.conname LIKE '%debtor%'
                           OR c.conname LIKE '%creditor%')
                  LOOP
                    EXECUTE 'ALTER TABLE monopoly.game_sessions DROP CONSTRAINT ' || quote_ident(r.conname);
                  END LOOP;
                END $$;
                """);

        patch("""
                SET search_path TO monopoly, public;
                DO $$
                DECLARE r record;
                BEGIN
                  FOR r IN
                    SELECT c.conname AS conname, t.relname AS tbl
                    FROM pg_constraint c
                    JOIN pg_class t ON c.conrelid = t.oid
                    WHERE t.relname LIKE 'game_%'
                      AND c.contype = 'f'
                      AND (c.conname LIKE '%position%'
                           OR c.conname LIKE '%tile%'
                           OR c.conname LIKE '%card%')
                  LOOP
                    EXECUTE 'ALTER TABLE monopoly.' || quote_ident(r.tbl)
                            || ' DROP CONSTRAINT ' || quote_ident(r.conname);
                  END LOOP;
                  -- Dodatkowo: dowolny FK z tabel game_* wskazujacy na katalog 'properties'
                  FOR r IN
                    SELECT c.conname AS conname, t.relname AS tbl
                    FROM pg_constraint c
                    JOIN pg_class t ON c.conrelid = t.oid
                    JOIN pg_class rt ON c.confrelid = rt.oid
                    WHERE t.relname LIKE 'game_%'
                      AND c.contype = 'f'
                      AND rt.relname = 'properties'
                  LOOP
                    EXECUTE 'ALTER TABLE monopoly.' || quote_ident(r.tbl)
                            || ' DROP CONSTRAINT ' || quote_ident(r.conname);
                  END LOOP;
                END $$;
                """);

        patch("""
                SET search_path TO monopoly, public;
                ALTER TABLE game_players
                    ADD COLUMN IF NOT EXISTS ready boolean NOT NULL DEFAULT false
                """);
        patch("""
                SET search_path TO monopoly, public;
                ALTER TABLE game_players
                    ADD COLUMN IF NOT EXISTS doubles_count integer NOT NULL DEFAULT 0
                """);
        patch("""
                SET search_path TO monopoly, public;
                ALTER TABLE game_sessions
                    ADD COLUMN IF NOT EXISTS leader_id bigint
                """);
        patch("""
                SET search_path TO monopoly, public;
                CREATE TABLE IF NOT EXISTS game_invites (
                    id bigserial PRIMARY KEY,
                    session_id bigint NOT NULL,
                    inviter_id bigint NOT NULL,
                    invitee_id bigint NOT NULL,
                    status varchar(16) NOT NULL DEFAULT 'PENDING',
                    created_at timestamp NOT NULL DEFAULT now()
                )
                """);
        patch("""
                SET search_path TO monopoly, public;
                ALTER TABLE game_players
                    ADD COLUMN IF NOT EXISTS rolls_this_turn integer NOT NULL DEFAULT 0
                """);
        patch("""
                SET search_path TO monopoly, public;
                ALTER TABLE game_players
                    ADD COLUMN IF NOT EXISTS double_rent_next boolean NOT NULL DEFAULT false
                """);
        patch("""
                SET search_path TO monopoly, public;
                ALTER TABLE game_players
                    ADD COLUMN IF NOT EXISTS jail_pass_active boolean NOT NULL DEFAULT false
                """);
        patch("""
                SET search_path TO monopoly, public;
                ALTER TABLE player_statistics
                    ADD COLUMN IF NOT EXISTS pending_wheel_card varchar(40)
                """);
        patch("""
                SET search_path TO monopoly, public;
                ALTER TABLE player_statistics
                    ADD COLUMN IF NOT EXISTS pending_start_cash_bonus integer NOT NULL DEFAULT 0
                """);
        patch("""
                SET search_path TO monopoly, public;
                ALTER TABLE game_sessions
                    ADD COLUMN IF NOT EXISTS pending_buyback_pos integer
                """);
        patch("""
                SET search_path TO monopoly, public;
                ALTER TABLE game_sessions
                    ADD COLUMN IF NOT EXISTS pending_buyback_victim_id bigint
                """);
        patch("""
                SET search_path TO monopoly, public;
                ALTER TABLE game_sessions
                    ADD COLUMN IF NOT EXISTS pending_buyback_holder_id bigint
                """);
        patch("""
                SET search_path TO monopoly, public;
                ALTER TABLE game_sessions
                    ADD COLUMN IF NOT EXISTS pending_buyback_price integer
                """);
        patch("""
                SET search_path TO monopoly, public;
                ALTER TABLE users
                    ADD COLUMN IF NOT EXISTS suspended boolean DEFAULT false
                """);
        patch("""
                SET search_path TO monopoly, public;
                UPDATE users SET suspended = false WHERE suspended IS NULL
                """);
        patch("""
                SET search_path TO monopoly, public;
                ALTER TABLE users
                    ALTER COLUMN suspended SET DEFAULT false
                """);
        patch("""
                SET search_path TO monopoly, public;
                ALTER TABLE users
                    ALTER COLUMN suspended SET NOT NULL
                """);
        patch("""
                SET search_path TO monopoly, public;
                ALTER TABLE users
                    ADD COLUMN IF NOT EXISTS suspended_until timestamp
                """);
        patch("""
                SET search_path TO monopoly, public;
                ALTER TABLE users
                    ADD COLUMN IF NOT EXISTS suspension_reason varchar(500)
                """);
        patch("""
                SET search_path TO monopoly, public;
                CREATE TABLE IF NOT EXISTS user_warnings (
                    id bigserial PRIMARY KEY,
                    user_id bigint NOT NULL,
                    moderator_id bigint NOT NULL,
                    message varchar(500) NOT NULL,
                    created_at timestamp NOT NULL DEFAULT now()
                )
                """);
        patchUsersDateOfBirthPostgres();
    }

    private void patchUsersDateOfBirthPostgres() {
        patch("""
                SET search_path TO monopoly, public;
                ALTER TABLE users ADD COLUMN IF NOT EXISTS date_of_birth date
                """);
        patch("""
                SET search_path TO monopoly, public;
                UPDATE users
                SET date_of_birth = (CURRENT_DATE - (age * INTERVAL '1 year'))::date
                WHERE date_of_birth IS NULL
                  AND EXISTS (
                    SELECT 1 FROM information_schema.columns
                    WHERE table_schema = current_schema()
                      AND table_name = 'users'
                      AND column_name = 'age'
                  )
                """);
        patch("""
                SET search_path TO monopoly, public;
                UPDATE users SET date_of_birth = (CURRENT_DATE - INTERVAL '25 years')::date
                WHERE date_of_birth IS NULL
                """);
        patch("""
                SET search_path TO monopoly, public;
                ALTER TABLE users ALTER COLUMN date_of_birth SET NOT NULL
                """);
        patch("""
                SET search_path TO monopoly, public;
                ALTER TABLE users DROP COLUMN IF EXISTS age
                """);
    }

    private boolean isH2() {
        try (Connection c = jdbcTemplate.getDataSource().getConnection()) {
            return c.getMetaData().getDatabaseProductName().toLowerCase().contains("h2");
        } catch (SQLException ex) {
            log.warn("Could not detect database type: {}", ex.getMessage());
            return false;
        }
    }

    private void patch(String sql) {
        try {
            jdbcTemplate.execute(sql);
        } catch (Exception ex) {
            log.warn("Schema patch skipped: {} — {}", ex.getMessage(), sql.trim().lines().findFirst().orElse(""));
        }
    }
}
